---
title: "Innovative Data Exploration with LASSO: Unveiling Patterns in Earnings and Education"
authors:
  - name: Muhammad Usman Aslam
  - name: Ishrath Jahan
  - name: Sai Kumar Miryala
  - name: Nikhitha Amireddy
  
date: 'today'
format:
  revealjs:
    incremental: true   
    slide-number: true
    show-slide-number: print
    smaller: true
    scrollable: true
    theme: moon
course: STA 6257 - Advanced Statistical Modeling
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

##  What is LASSO Regression?

LASSO (Least Absolute Shrinkage and Selection Operator), introduced by Robert Tibshirani in 1996 [@Tibshirani1996].

LASSO regression, also known as L1 regularization, is a popular technique used in statistical modeling and machine learning to estimate the relationships between variables and make predictions. 


## How LASSO Regression Works?


::: {.panel-tabset}

### Linear regression model

LASSO regression starts with the standard linear regression model, which assumes a linear relationship between the independent variables (features) and the dependent variable (target).

$$
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \ldots + \beta_n x_n + \epsilon
$$
y is the dependent variable (target).
β₀, β₁, β₂, ..., βₚ are the coefficients (parameters) to be estimated.
x₁, x₂, ..., xₚ are the independent variables (features).
ε represents the error term.

### L1 regularization

LASSO regression introduces an additional penalty term based on the absolute values of the coefficients.

The choice of the regularization parameter λ is crucial in LASSO regression:

- At $\lambda = 0$, LASSO equals an ordinary least squares regression, offering no coefficient shrinkage.

-  A larger λ value increases the amount of regularization, leading to more coefficients being pushed towards zero, which simplifies the model and focuses on the most impactful variables.

### Shrinking coefficients

By adding the L1 regularization term, LASSO regression can shrink the coefficients towards zero. 

When λ is sufficiently large, some coefficients are driven to exactly zero. This property of LASSO makes it useful for feature selection, as the variables with zero coefficients are effectively removed from the model.

:::


## Literature Review

LASSO regression’s versatility across multiple fields illustrates its capability to manage complex datasets effectively, particularly with continuous outcomes.

**Applications Across Fields**

::: {.panel-tabset}

### Economics

Zhou et al. [Zhou2022] highlighted LASSO’s ability to identify key economic predictors that assist in strategic decision-making. 

This example underscores its utility in economic analysis, where it helps to isolate factors that directly influence continuous economic outcomes like wages, prices, or economic growth.

### Bioinformatics

Lu et al. and Musoro [@Lu2011; @Musoro2014] used LASSO regression to develop models based on gene expression data, advancing our understanding of genetic influences on continuous traits and diseases. Their work illustrates how LASSO can handle vast amounts of biological data to pinpoint critical genetic pathways.


### Public Health

McEligot et al. (2020)[@McEligot2020] employed logistic LASSO to explore how dietary factors, which vary continuously, affect the risk of developing breast cancer. Their findings highlight LASSO's strength in dealing with complex, high-dimensional datasets in health sciences.

:::

## Methodology

## Data Description

## Statistical Modeling

## Results 

## Conclusion

## Implications and Future Directions

